apiVersion: v1
kind: Namespace
metadata:
  name: evcharge-secure
  labels:
    app.kubernetes.io/name: evchargesecure
    app.kubernetes.io/part-of: smart-grid
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
