apiVersion: v1
kind: Secret
metadata:
  name: evcharge-secrets
  namespace: evcharge-secure
  labels:
    app.kubernetes.io/name: evchargesecure
type: Opaque
stringData:
  EV_SECRET_KEY: "prod-evcharge-k8s-secret-9d8a7c6b5e4f3a210fedcba987654321"
